### ISSUE TITLE
Unable to import default validations and messageMap

### ISSUE THREAD

**Issue by brianhilst** [voletiswaroop/react-material-ui-form#10]
I have not been able to import the default field validations and messageMap following the demo example.  I'm trying to do this from a typescript based React application.  Can you give an example that imports directly from the component using this rather than via the src/index.js file?

**Comment by voletiswaroop** [comment]
You can able to import the default field validations messages by using: 
import { messageMap } from 'react-material-ui-form/dist/validation/index';
rest everything is same.

const customFormMsg = Object.assign(messageMap, { 
  isEmail: 'Please enter a valid email address',  
  isLength:'Must be 2-50 characters', 
})

<MaterialUIForm onSubmit={this.submit} validation={{ messageMap: customFormMsg}}></MaterialUIForm>
