### ISSUE TITLE
TextField doesn't update if value is changed

### ISSUE THREAD

**Issue by brianhilst** [voletiswaroop/react-material-ui-form#11]
I have a form where the value for a TextField is updated after the form is initial rendered; however, the TextField value does not display the updated value when it is within the MaterialUIForm.  I am using mobx and the component is observing the user object used below for the value.  If I put that same value code in a <div>, it updates correctly.  I suspect this has something to do with the field cloning.  Is there some way to get this to work?

<TextField
            label="First name"
            type="text"
            data-validators="isRequired"
            value={user ? user.firstName : ""}
/>
<div>First Name: {user ? user.firstName : ""}</div>

**Comment by brianhilst** [comment]
I happened to look at the original project this one is based on and it appears this same issue was raised there (https://github.com/galki/material-ui-form/issues/67)

**Comment by voletiswaroop** [comment]
Hi @brianhilst ,
I understand your problem, let me look into this and ill get back to you soon.

**Comment by voletiswaroop** [comment]
Hi @brianhilst ,
Same condition im using in one of the projects but i have stored the value in variable and assigned that to value attributed.

Ex:
let userName = user ? user.firstName : "";

<TextField
label="First name"
type="text"
data-validators="isRequired"
value={userName}
/>
