### ISSUE TITLE
Reset form on submit

### ISSUE THREAD

**Issue by finbar123** [voletiswaroop/react-material-ui-form#13]
Hi

Excellent forms processor, I was wondering how to reset the form after a submit has been completed, ie just mimicking the  Reset Button on your example.
Thanks

Finbar

**Comment by voletiswaroop** [comment]
Hi @finbar123 ,
Even I have the same use case in my current project, I achieved it with the help of react ref's.

Here the code snippet:

1. Declared ref under constructor:- this.myref = React.createRef();
2. Created reset button and hide it using css:-  
     - <button variant="raised" type="reset" className='hide' ref={this.myref}>Reset</button>
3. End of submit function programittically clicked reset button:- this.myref.current.click();


I think this solves your problem. Feel free to re-open this ticket if your feeling this doesn't solve your problem.

Thanks,
Swaroop

**Comment by finbar123** [comment]
Swaroop

 

Hi thanks for the reply that does the trick for me 

 

Thanks

 

Finbar
