### ISSUE TITLE
Doesn't work on latest MUI version

### ISSUE THREAD

**Issue by C-Higgins** [voletiswaroop/react-material-ui-form#18]
It seems the data structure of the MUI components has changed for name. When using a TextField, the error 'FieldClone does not support native elements' will be thrown. This is because you are checking 
```js
    if (fieldComp.type.name === undefined) {
      throw new Error('FieldClone does not support native elements');
    }
```

However, the name now resides in `fieldComp.type.options.name`

**Comment by C-Higgins** [comment]
Upon further digging there are quite a lot of things that don't work in this package with latest MUI version. Would recommend putting that in the README to avoid future issues being opened

**Comment by devolt5** [comment]
Same here.

I don't know if this is just related to functional components, but as the newest MUI forces you to use functional components (and not class components any more), this is quite serious :(

**Comment by voletiswaroop** [comment]
Updated README file as @C-Higgins  suggested.
