### ISSUE TITLE
Error: FieldClone does not support native elements

### ISSUE THREAD

**Issue by jessequinn** [voletiswaroop/react-material-ui-form#20]
Hi guys,

Great work here, but i am having an issue following the example for nested fields.

I receive the following error

```
Error: FieldClone does not support native elements
```

Any ideas how to fix this?

My `package.json`

```
  "dependencies": {
    "@material-ui/core": "^4.3.2",
    "@material-ui/icons": "^4.2.1",
    "@material-ui/styles": "^4.3.0",
    "final-form": "^4.18.4",
    "lodash": "^4.17.15",
    "node-sass": "^4.12.0",
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "react-final-form": "^6.3.0",
    "react-material-ui-form": "^1.1.4",
    "react-scripts": "3.1.0",
    "styled-components": "^4.3.2"
  },
```

**Comment by LuisAguilarPena** [comment]
I got the same issue and these are some of my findings: react-material-ui-form, comes with a required sub dependency which is @material-ui/core 3.1.1. Directly adding MUI's dependency to your package.json seems to be causing this error.

**Comment by voletiswaroop** [comment]
Yes you are right @LuisAguilarPena currently this package can support till @material-ui v3. 
Currently i'm engaged with other project works, so i'm not getting enough time to supporting till v4.

@jessequinn you need to downgrade you are "@material-ui/core": "^4.3.2" to @material-ui/core 3.1.1 to work 'react-material-ui-form' package as expected.
