### ISSUE TITLE
eh? what? how?

### ISSUE THREAD

**Issue by webpolis** [voletiswaroop/react-material-ui-form#28]
I honestly don't know how to begin using this library. The README looks like cryptic "lorem ipsum" to me.

**Comment by voletiswaroop** [comment]
Hi @webpolis,
Its very simple install the component using 'npm i react-material-ui-form' then simply follow the examples sections. 

Ex: If you want to create a simple subscriber form, so basically you need two things
- Input field 
- Button 
both are include inside form tag. 

Here are example code for subscriber form:

`
import MaterialUIForm from 'react-material-ui-form'
const customFormMsg = Object.assign(messageMap, { 
  isEmail: 'Please enter a valid email address',  
  isLength:'Must be 2-50 characters', 
})
class subscriberForm extends React.Component {
  submit = (values, pristineValues) => {
    // get all values and pristineValues on form submission
  }
render() {
  return (
    <MaterialUIForm onSubmit={this.submit} validation={{ messageMap: customFormMsg}}>
      <TextField label="Name" type="text" name="FirstName" value="Name" data-validators="isLength" />
      <TextField label="Email" type="text" name="Email" value="abc@xyz.com" data-validators="isRequired,isEmail" />
      <Button variant="raised" type="submit">Submit</Button>
    </MaterialUIForm>
    )
  }
} 
`
