### ISSUE TITLE
Seems to skip validation when enter key is pressed

### ISSUE THREAD

**Issue by futurepirateking** [voletiswaroop/react-material-ui-form#4]
Whenever I press on the submit button, it validates fine. However, when I press enter, it submits the form without validating.

```
<MaterialUIForm onSubmit={this.submit}
        validation={{ messageMap: customMessageMap, validators}}  className={classes.container}>

        <FormGroup>

          <FacebookLoginButton />
          <GoogleLoginButton />

          <TextField
            autoFocus
            value=""
            type="email"
            name="email"
            label="Email Address"
            className={classes.textField}
            data-validators="isRequired,isEmail"
            onChange={this.customInputHandler}
            margin="normal"
          />

          <TextField
            type="password"
            name="password"
            label="Password"
            value=""
            className={classes.textField}
            data-validators="isRequired, isPassword"
            onChange={this.customInputHandler}
            margin="normal"
          />

          <FormControlLabel
            control={<Checkbox name="rememberMe" color="default" defaultChecked={this.state.rememberMe} onChange={this.updateRememberMe} />}
            label="Remember Me"
          />

          <Button type="submit" color="default" variant="raised">
            Login
          </Button>

        </FormGroup>

      </MaterialUIForm>
```

Plus, it seems that customToggleHandler doesn't work with FormControlLabel. I might be doing it wrong though. Everything returns invalid.

```
<FormControlLabel 
control={
<Checkbox name="rememberMe" color="default" value="yes" onChange={this.customToggleHandler } />
}
label="Remember Me"
/>
```

**Comment by voletiswaroop** [comment]
Hi @kobeissi2 ,

> Whenever I press on the submit button, it validates fine. However, when I press enter, it submits the form without validating.
> 
> ```
> <MaterialUIForm onSubmit={this.submit}
>         validation={{ messageMap: customMessageMap, validators}}  className={classes.container}>
> 
>         <FormGroup>
> 
>           <FacebookLoginButton />
>           <GoogleLoginButton />
> 
>           <TextField
>             autoFocus
>             value=""
>             type="email"
>             name="email"
>             label="Email Address"
>             className={classes.textField}
>             data-validators="isRequired,isEmail"
>             onChange={this.customInputHandler}
>             margin="normal"
>           />
> 
>           <TextField
>             type="password"
>             name="password"
>             label="Password"
>             value=""
>             className={classes.textField}
>             data-validators="isRequired, isPassword"
>             onChange={this.customInputHandler}
>             margin="normal"
>           />
> 
>           <FormControlLabel
>             control={<Checkbox name="rememberMe" color="default" defaultChecked={this.state.rememberMe} onChange={this.updateRememberMe} />}
>             label="Remember Me"
>           />
> 
>           <Button type="submit" color="default" variant="raised">
>             Login
>           </Button>
> 
>         </FormGroup>
> 
>       </MaterialUIForm>
> ```

I have tested in MAC system, I'm unable to reproduce the issue.

> Plus, it seems that customToggleHandler doesn't work with FormControlLabel. I might be doing it wrong though. Everything returns invalid.
> 
> ```
> <FormControlLabel 
> control={
> <Checkbox name="rememberMe" color="default" value="yes" onChange={this.customToggleHandler } />
> }
> label="Remember Me"
> />
> ```

The above checkbox implementation is wrong.

If you want to use checkbox inside <FormControlLabel> you have to pass state of the checkbox into the customToggleHandler function.

For further assistance refer this document: https://material-ui.com/demos/selection-controls/
