### ISSUE TITLE
How to prevent validation when clicking non-submit buttons?

### ISSUE THREAD

**Issue by brianhilst** [voletiswaroop/react-material-ui-form#9]
When clicking the Cancel button, it is confusing to see validated fields flash red briefly as the dialog is closing even though they are still in a pristine state.  Is there a way to prevent field validation from occurring when clicking on a button other than the submit button?  Alternatively, is there a way to only do validation when the submit button is clicked?

**Comment by voletiswaroop** [comment]
Use <Button variant="raised" type="reset">Cancel</Button> instead of cancel button. So that it will not submit the form. 
If it is not satisfying your requirement, Feel free to reopen the issue.
